version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.23
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-25-182.compute-1.amazonaws.com
            database: darcv7unemngco
            ssl: true
            user: qqzehliuftnvuw
            password: c94b5643588860f6160898e7a9d819bc9389c1eb8348c5dbef74aa7ae27fbc21
            rawAccess: true
            port: '5432'
            migrations: true